openapi: "3.0.3"
info:
  title: "Data WH"
  version: "1.0.0"
  description: "La api de un sistema de manejo de contactos"
  contact:
    name: Mariano Fernández
servers:
  - url: "http://localhost:3500/api/v1/"

paths:
  /usuarios:
    get:
      summary: "Acceso a listado de Usuarios"
      tags:
        - "Usuarios"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#components/schemas/Usuario"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"
  /usuario/login:
    post:
      summary: "Login de Usuarios"
      tags:
        - "Usuarios"
      requestBody:
        description: "Nombre de usuario y password"
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
                - email
                - password
              properties:
                email:
                  type: "string"
                  example: email@email.com
                password:
                  type: "string"
                  example: "12345678"
      responses:
        "200":
          description: "Login OK"
          content:
            text/plain:
              schema:
                type: string
                description: JWT Token
                example: "eYhb1NiIsGciOiJIUzII..."
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "500":
          $ref: "#components/responses/ErrorServidor"
  /usuario:
    post:
      summary: "Cargar un usuario"
      tags:
        - "Usuarios"
      requestBody:
        description: "Los detalles del usuario"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Usuario"
      responses:
        "200":
          description: "Todo OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Usuario"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "500":
          $ref: "#components/responses/ErrorServidor"

  /usuario/{id_usuario}:
    put:
      summary: "Modificar Usuario por id"
      tags:
        - "Usuarios"
      requestBody:
        description: "Los detalles del usuario"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Usuario"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Usuario"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"
    delete:
      summary: "Borrar Usuario"
      tags:
        - "Usuarios"
      parameters:
        - name: id_usuario
          required: true
          in: path
          schema:
            type: "integer"
      responses:
        "200":
          description: "OK"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"

  /empresas:
    get:
      summary: "Acceso a listado de Empresas"
      tags:
        - "Empresas"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#components/schemas/Empresa"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"
  /empresa:
    post:
      summary: "Cargar una empresa"
      tags:
        - "Empresas"
      requestBody:
        description: "Los detalles de la empresa"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Empresa"
      responses:
        "200":
          description: "Todo OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empresa"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "500":
          $ref: "#components/responses/ErrorServidor"
    put:
      summary: "Modificar Empresa por nombre"
      tags:
        - "Empresas"
      requestBody:
        description: "Los detalles de la empresa"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Empresa"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Empresa"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"
    delete:
      summary: "Borrar Empresa"
      tags:
        - "Empresas"
      parameters:
        - name: empresa
          required: true
          in: path
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"

  /ubicaciones:
    get:
      summary: "Acceso a listado de Ubicaciones"
      tags:
        - "Ubicaciones"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#components/schemas/Ubicacion"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"
  /ubicacion:
    post:
      summary: "Cargar una ubicación"
      tags:
        - "Ubicaciones"
      requestBody:
        description: "Los detalles de la ubicación"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ubicacion"
      responses:
        "200":
          description: "Todo OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ubicacion"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "500":
          $ref: "#components/responses/ErrorServidor"
    put:
      summary: "Modificar ubicación por ciudad"
      tags:
        - "Ubicaciones"
      requestBody:
        description: "Los detalles de la ubicación"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ubicacion"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Ubicacion"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"
  /ubicacion/{ciudad}:
    delete:
      summary: "Borrar Ubicación"
      tags:
        - "Ubicaciones"
      parameters:
        - name: ciudad
          required: true
          in: path
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"

  /contactos:
    get:
      summary: "Acceso a listado de Contactos"
      tags:
        - "Contactos"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#components/schemas/Contacto"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"
  /contacto:
    post:
      summary: "Cargar un contacto"
      tags:
        - "Contactos"
      requestBody:
        description: "Los detalles del contacto"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contacto"
      responses:
        "200":
          description: "Todo OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contacto"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "500":
          $ref: "#components/responses/ErrorServidor"
  /contacto/{id_contacto}:
    put:
      summary: "Modificar Contacto por id"
      tags:
        - "Contactos"
      parameters:
        - name: id_contacto
          required: true
          in: path
          schema:
            type: "string"
      requestBody:
        description: "Los detalles del contacto"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contacto"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Contacto"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"
    delete:
      summary: "Borrar Contacto"
      tags:
        - "Contactos"
      parameters:
        - name: id_contacto
          required: true
          in: path
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          $ref: "#components/responses/DatosFaltantes"
        "401":
          $ref: "#components/responses/SinAcceso"
        "403":
          $ref: "#components/responses/NoAutorizado"
        "500":
          $ref: "#components/responses/ErrorServidor"

tags:
  - name: "Usuarios"
    description: "ABM de usuarios y login"
  - name: "Empresas"
    description: "ABM de empresas"
  - name: "Ubicaciones"
    description: "ABM de ubicaciones"
  - name: "Contactos"
    description: "ABM de contactos"

components:
  schemas:
    Usuario:
      type: "object"
      required:
        - nombre_usuario
        - nombre_completo
        - email
        - password
        - perfil
      properties:
        nombre_completo:
          type: "string"
          example: "Juan Pérez"
        nombre_usuario:
          type: "string"
          example: jperez
        direccion:
          type: "string"
          example: "Marcelo T. Alvear 1614 4°A"
        password:
          type: "string"
          example: "12345678"
        email:
          type: "string"
          example: juan@perez.com
        perfil:
          type: "string"
          enum:
            - Básico
            - Admin

    Empresa:
      type: "object"
      required:
        - nombre
        - ciudad
        - pais
        - email
        - telefono
        - direccion
      properties:
        nombre:
          type: "string"
          example: "Compañía X"
        ciudad:
          type: "string"
          example: "Buenos Aires"
        país:
          type: "string"
          example: "Argentina"
        email:
          type: "string"
          example: "email@email.com"
        telefono:
          type: "string"
          example: "54 11 5464 4455"
        direccion:
          type: "string"
          example: "Marcelo T. Alvear 1614 4°A"


    Ubicacion:
      type: "object"
      required:
        - region
        - pais
        - ciudad
      properties:
        region:
          type: "string"
          example: "América del Sur"
        pais:
          type: "string"
          example: Argentina
        ciudad:
          type: "string"
          example: "Buenos Aires"


    Contacto:
      type: "object"
      required:
        - nombre
        - apellido
        - empresa
        - cargo
        - email
        - region
        - pais
        - ciudad
        - interes
        - canalPreferido
        - canales
      properties:
        nombre:
          type: "string"
          example: "Juan"
        apellido:
          type: "string"
          example: "Pérez"
        empresa:
          type: "string"
          example: "Compañía X"
        cargo:
          type: "string"
          example: "Presidente"
        email:
          type: "string"
          example: "juan@perez.com"
        region:
          type: "string"
          example: "América del Sur"
        pais:
          type: "string"
          example: "Argentina"
        ciudad:
          type: "string"
          example: "Buenos Aires"
        interes:
          type: "integer"
          example: 30
        canalPreferido:
          type: "string"
          example: "Whatsapp"
        canales:
          type: "object"
          properties: 
            canal: 
              type: "integer"
              example: "Whatsapp"
            cuenta:
              type: "string"
              example: "+54 11 2545 5461"  
            preferencia:
              type: "string"
              enum: ["No molestar", "Sin preferencia", "Canal preferido"]

  responses:
    SinAcceso:
      description: El token de acceso no es válido o está vacío.
    NoAutorizado:
      description: No está autorizado a realizar la operación.
    ErrorServidor:
      description: Se produjo un error al procesar la operación, reintente.
    DatosFaltantes:
      description: Los datos enviados son incorrectos o incompletos, reintente.

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
